# Site settings
baseURL = "https://clancambion.org/"
languageCode = "en-us"
title = "Clan Cambion"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Your name"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Clan Cambion"
    subtitle = "An SCA Household"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "/"

    [[params.navigation.links]]
      name = "Blogs"
      url = "blogs"

    [[params.navigation.links]]
      name = "What is a household?"
      url = "/household/"

    [[params.navigation.links]]
      name = "Our Members"
      url = "/mbmers/"

    [[params.navigation.links]]
      name = "Our Activities"
      url = "/activities/"

    [[params.navigation.links]]
        name = "Our Pennsic Encampment"
        url = "/pennsic/"

    [[params.navigation.links]]
        name = "Our Values"
        url = "/values/"

    [[params.navigation.links]]
        name = "Our History"
        url = "/history/"

    [[params.navigation.links]]
        name = "Our Traditions"
        url = "/Traditions/"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Get Started"
      url = "/blogs"

    # Button Style 2
    [[params.navigation.button2]]
      name = "Log In"
      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Welcome, from Clan Cambion"
    subtitle = "Grab some food and let us sing you a song"
    buttonText = "Meet Us"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "What is a household?"
      subtitle = "Friends & Family"
      image = "castle.jpg"
      url = "household/"

    [[params.tiles.showcase]]
      title = "Our Members"
      subtitle = "Get to know us"
      image = "cambion-members.jpg"
      url = "members/"

    [[params.tiles.showcase]]
      title = "Our Activities"
      subtitle = "Camping, Cooking, & Crooning"
      image = "music.jpg"
      url = "activities/"

    [[params.tiles.showcase]]
      title = "Our Pennsic Encampment"
      subtitle = "Centrally-located & Family-friendly"
      image = "pennsic-gate.jpg"
      url = "pennsic/"

    [[params.tiles.showcase]]
      title = "Our Traditions"
      subtitle = "How we do things"
      image = "drinking-horn.jpg"
      url = "traditions/"

    [[params.tiles.showcase]]
      title = "Our History"
      subtitle = "How we got here"
      image = "old-cambion.jpg"
      url = "history/"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = false
    title = "Massa libero"
    subtitle = """Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
    Mauris aliquet magna magna sed nunc rhoncus pharetra.
    Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor.
    Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.
    Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."""
    buttonText = "Get Started"
    url = "/blogs"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Clan Cambion"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-envelope-o"
      url= "https://groups.io/g/clan-cambion"
      label = "Email group"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
